### Rota Raiz do App
GET http://localhost:3000/

### Lista todos os Users
GET http://localhost:3000/users

### Insere um novo User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Tatiana",
  "email": "tatiana@example.com"
}

### Insere um novo User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Wladimir",
  "email": "wladimir@example.com"
}

### Lista um User específico
GET http://localhost:3000/users/b58662a3-e52c-4d2f-85b0-19829763c666


### Atualiza um User específico
PUT http://localhost:3000/users/b58662a3-e52c-4d2f-85b0-19829763c666
Content-Type: application/json

{
  "name": "Wladimir Santos",
  "email": "wladimir@example.com"
}

### Deleta um User específico
DELETE http://localhost:3000/users/71bf257c-94fc-44cb-9e11-1b858a9abe13
