### Rota Raiz do App
GET http://localhost:3000/

### Lista todos os Users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2RiNmJiZi1jOWJkLTQ3NTgtODM4Yy1hYWJhZjU1YmE4YmMiLCJlbWFpbCI6IndsYWRpbWlyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2MzMxNDI3LCJleHAiOjE3NTYzMzg2MjcsImF1ZCI6ImZsb3dnZXN0LWFwcCIsImlzcyI6ImZsb3dnZXN0IiwianRpIjoiNzQwNzFjNjgtNzFhOS00YjU2LWJhMjctYmI1YzMwM2QyZTQ3In0.5f9unalzZnx4E2gAwFtgkxi9FQ_tsN0UMJN7JBXx6tQ
Content-Type: application/json

### Insere um novo User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Tat",
  "email": "tatiana@example.com",
  "password": "123456"
}

### Insere um novo User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Wladimir",
  "email": "wladimir@example.com",
  "password": "123456"
}

### Lista um User específico
GET http://localhost:3000/users/13db6bbf-c9bd-4758-838c-aabaf55ba8bc


### Atualiza um User específico
PUT http://localhost:3000/users/13db6bbf-c9bd-4758-838c-aabaf55ba8bc
Content-Type: application/json

{
  "name": "Wladimir Santos",
  "email": "wladimir@example.com"
}

### Deleta um User específico
DELETE http://localhost:3000/users/0483785f-f456-4e88-bc79-06d9829f2be0

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "wladimir@example.com",
  "password": "123456"
}

### Refresh token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2RiNmJiZi1jOWJkLTQ3NTgtODM4Yy1hYWJhZjU1YmE4YmMiLCJlbWFpbCI6IndsYWRpbWlyQGV4YW1wbGUuY29tIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NTYzMjgyMzQsImV4cCI6MTc1NjkzMzAzNCwiYXVkIjoiZmxvd2dlc3QtYXBwIiwiaXNzIjoiZmxvd2dlc3QifQ.wUDcKXkxrgddePKqTI4SVrfzH9VpyZ3VGeC3Xjwbn70"
}

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2RiNmJiZi1jOWJkLTQ3NTgtODM4Yy1hYWJhZjU1YmE4YmMiLCJlbWFpbCI6IndsYWRpbWlyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2MzMxNDI3LCJleHAiOjE3NTYzMzg2MjcsImF1ZCI6ImZsb3dnZXN0LWFwcCIsImlzcyI6ImZsb3dnZXN0IiwianRpIjoiNzQwNzFjNjgtNzFhOS00YjU2LWJhMjctYmI1YzMwM2QyZTQ3In0.5f9unalzZnx4E2gAwFtgkxi9FQ_tsN0UMJN7JBXx6tQ
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2RiNmJiZi1jOWJkLTQ3NTgtODM4Yy1hYWJhZjU1YmE4YmMiLCJlbWFpbCI6IndsYWRpbWlyQGV4YW1wbGUuY29tIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NTYzMjgyOTgsImV4cCI6MTc1NjkzMzA5OCwiYXVkIjoiZmxvd2dlc3QtYXBwIiwiaXNzIjoiZmxvd2dlc3QifQ.7IuhNX0a1L63KEERL8OUTvid2cLEpoUVKX0sAFkLbKo"
}